<a href="https://colab.research.google.com/github/Sachinramesh15/Car_Parking_system/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#create tensors with tf.constant
scalar=tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
matrix= tf.constant([[1.,2.],
                    [2.,1]], dtype=tf.float16)
matrix

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 1.]], dtype=float16)>

In [ ]:
#create tensors with tf.variable
matrix=tf.Variable([1,2])
matrix[0].assign(10)#variable tensors can be reassigned but not constant
matrix

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  2], dtype=int32)>

In [ ]:
random= tf.random.Generator.from_seed(42)
random1=random.normal(shape=(3,2))
tf.random.set_seed(42)# global random seed, fix tensors(not random)
tf.random.shuffle(random1, seed=42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.ones(shape=(3,3) )

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
import numpy as np
array=np.arange(1,25,dtype=np.int32)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(array, shape=(8,3))
A

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

In [ ]:
B=A[...,tf.newaxis]#adds new dimension
B[:-1,:-1]


<tf.Tensor: shape=(7, 2, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2]],

       [[ 4],
        [ 5]],

       [[ 7],
        [ 8]],

       [[10],
        [11]],

       [[13],
        [14]],

       [[16],
        [17]],

       [[19],
        [20]]], dtype=int32)>

In [ ]:
tf.expand_dims(A,axis=0)

<tf.Tensor: shape=(1, 8, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]], dtype=int32)>

In [ ]:
tensor=tf.constant([[10,2],[2,10]])
tensor2=tensor+10
tensor3=tf.multiply(tensor,10)
tensor2,tensor3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 12],
        [12, 20]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  20],
        [ 20, 100]], dtype=int32)>)

In [ ]:
x=tf.constant([[1,2],[2,1]])
y=tf.constant([[2,1],[1,2]])
z=tf.matmul(x,y)
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [5, 4]], dtype=int32)>

In [ ]:
tf.transpose(z)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [5, 4]], dtype=int32)>

In [ ]:
#to change data type
x=tf.cast(x, dtype=tf.float16)
x

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1., 2.],
       [2., 1.]], dtype=float16)>

**Aggregate functions**


In [ ]:
agg=tf.constant(np.random.randint(0,100,size=20))
print(f"agg:{agg}")
print(f"max value:{tf.reduce_max(agg)}")
print(f"min value:{tf.reduce_min(agg)}")
print(f"sum value:{tf.reduce_sum(agg)}")


agg:[28 98 47 57 23 77 75 74 96 82 95 84  5 41 75 40 68 32 10 57]
max value:98
min value:5
sum value:1164


In [ ]:
import tensorflow_probability as tfp
print(f"variance value:{tfp.stats.variance(agg)}")
#tf.math.reduce_variance(tf.cast(agg, dtype=tf.float16)) alternate way to find variance
print(f"standard deviation value:{tf.math.reduce_std(tf.cast(agg, dtype=tf.float32))}")

variance value:780
standard deviation value:27.93671417236328


In [ ]:
print(f"positional max:{tf.math.argmax(agg)}")
print(f"positional min:{tf.math.argmin(agg)}")


positional max:1
positional min:12


In [ ]:
tf.random.set_seed(42)
E=tf.random.uniform(shape=[50])
E.numpy(),tf.math.argmax(E).numpy(),tf.math.argmin(E).numpy()

(array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32),
 42,
 16)

In [ ]:
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]), shape=[1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
#squeeze is used to remove single dimensions
G=tf.squeeze(G)
G,G.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

One-hot encoding

In [ ]:
list=[1,2,3,4]
tf.one_hot(list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>